# Generated by Django 4.1.2 on 2022-10-30 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Cart Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cart_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('cart_products', models.ManyToManyField(to='products_cart.cartproducts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shippingaddress')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
