# Generated by Django 4.1.2 on 2022-10-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0002_alter_cartproducts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
