# Generated by Django 4.1.2 on 2022-10-29 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_and_more'),
        ('dashboard', '0002_alter_shippingaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_cart', '0002_rename_created_date_productcart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products Cart',
            },
        ),
        migrations.AlterModelOptions(
            name='productcart',
            options={},
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='billed',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='total',
        ),
        migrations.AddField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCartItem',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='products_cart',
            field=models.ManyToManyField(to='products_cart.productcart'),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shippingaddress'),
        ),
    ]
