# Generated by Django 4.1.2 on 2022-10-30 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('products_cart', '0003_alter_cartproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
