# Generated by Django 4.1.2 on 2022-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0003_ordercart_alter_productcart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='products_cart',
            field=models.ManyToManyField(blank=True, null=True, to='products_cart.productcart'),
        ),
    ]
