# Generated by Django 4.1.2 on 2022-10-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0004_cartproducts_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
