# Generated by Django 4.1.2 on 2022-11-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_street_1',
            new_name='address_street',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_street_2',
            new_name='apartment_number',
        ),
    ]
