# Generated by Django 4.1.2 on 2022-11-20 23:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_shippingaddress_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='customer_avatar/'),
        ),
    ]
