# Generated by Django 4.1.2 on 2022-10-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
