# Generated by Django 4.1.2 on 2022-10-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Contact Us'},
        ),
    ]
