# Generated by Django 4.1.2 on 2022-11-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('cart_products', models.ManyToManyField(to='products_cart.cartproducts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='dashboard.shippingaddress')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
