# Generated by Django 4.1.2 on 2022-11-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0001_initial'),
        ('products_checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_products',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_cart.cartproducts'),
        ),
    ]
