# Generated by Django 4.1.2 on 2022-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0001_initial'),
        ('products_checkout', '0002_remove_order_cart_products_order_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_products',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_products',
            field=models.ManyToManyField(to='products_cart.cartproducts'),
        ),
    ]
