# Generated by Django 4.1.2 on 2022-11-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_address_street_1_shippingaddress_address_street_and_more'),
        ('products_checkout', '0003_remove_order_cart_products_order_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='dashboard.shippingaddress'),
        ),
    ]
