# Generated by Django 4.1.2 on 2022-10-20 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComments',
            new_name='ProductComment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
    ]
