# Generated by Django 4.1.2 on 2022-11-13 00:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_resized',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
