# Generated by Django 4.1.2 on 2022-11-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_resized',
        ),
    ]
