# Generated by Django 4.1.2 on 2022-10-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_deleted_subcategory_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_deleted',
        ),
    ]
